### ISSUE TITLE
this file should be removed together with DmtMailComment Handler

### ISSUE THREAD

**Issue by dmiric** [dreamfony/dv#12]
Ref. [docroot/profiles/dv/modules/custom/dmt_mail/config/install/inmail.handler.dmt_comment.yml:1](https://github.com/dreamfony/dv/blob/902128d5e208250e3c000ba8b5dbdad7a0dbe5e2/docroot/profiles/dv/modules/custom/dmt_mail/config/install/inmail.handler.dmt_comment.yml#L1)

```yml
# todo this file should be removed together with DmtMailComment Handler
langcode: en
status: false
id: dmt_comment
…
```

(automatically generated by [Github-Todos](https://github.com/naholyr/github-todos))
