### ISSUE TITLE
test inject issue

### ISSUE THREAD

**Issue by dmiric** [dreamfony/dv#4]
Ref. [blt/project.yml:90](https://github.com/dreamfony/dv/blob/e56451b36f748eec5ed9df4e7dab5321122f8ded/blt/project.yml#L90)

```yml
  # todo test inject issue
import-content:
  local:
    migrate:
…
```

(automatically generated by [Github-Todos](https://github.com/naholyr/github-todos))
