### ISSUE TITLE
#12 this file should be removed together with DmtMailComment Handler

### ISSUE THREAD

**Issue by dmiric** [dreamfony/dv#45]
Ref. [docroot/profiles/dv/modules/custom/dmt_mail/config/install/inmail.handler.dmt_comment.yml:1](https://github.com/dreamfony/dv/blob/0a4017fbd27585276a1aa5882d79801788dcb0a0/docroot/profiles/dv/modules/custom/dmt_mail/config/install/inmail.handler.dmt_comment.yml#L1)

```yml
# todo #12 this file should be removed together with DmtMailComment Handler
langcode: en
status: false
id: dmt_comment
…
```

(automatically generated by [Github-Todos](https://github.com/naholyr/github-todos))
