### ISSUE TITLE
test close issue

### ISSUE THREAD

**Issue by dmiric** [dreamfony/dv#5]
Ref. [blt/project.yml:90](https://github.com/dreamfony/dv/blob/8c454d6957609cc5c730a7b85743a80c6436b3d6/blt/project.yml#L90)

```yml
# todo test close issue
import-content:
  local:
    migrate:
…
```

(automatically generated by [Github-Todos](https://github.com/naholyr/github-todos))
